version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db
    networks:
      - reminder-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    depends_on:
      - mongo
    networks:
      - reminder-network

  reminder-app:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://admin:admin@mongo:27017/reminderapp?authSource=admin"
    depends_on:
      - mongo
    networks:
      - reminder-network

volumes:
    mongo-data:

networks:
  reminder-network:
    driver: bridge
